FROM public.ecr.aws/lambda/python:3.10


COPY lambda/requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt


COPY lambda/lambda_function.py ${LAMBDA_TASK_ROOT}
COPY Application/ ${LAMBDA_TASK_ROOT}/Application
COPY api_keys.sh ${LAMBDA_TASK_ROOT}/api_keys.sh

ARG OPENAI_API_key
ENV OPENAI_API_key=$OPENAI_API_key

ARG TELEGRAM_API_key
ENV TELEGRAM_API_key=$TELEGRAM_API_key

ARG BOOKING_API_key
ENV BOOKING_API_key=$BOOKING_API_key



CMD ["lambda_function.handler"]




